### ISSUE TITLE
Not compatible with Python 3?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/spotify-tensorflow#21]
Trying to `pip install` this in a Python 3 Tensorflow container and got the following error.
```
docker run -it --rm tensorflow/tensorflow:1.4.1-py3 /bin/bash
root@3b9ec0d480b2:/notebooks# pip install spotify_tensorflow
Collecting spotify_tensorflow
  Downloading spotify_tensorflow-0.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/util.py", line 249, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/packaging.py", line 737, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "/tmp/pip-build-bl_kidhk/spotify-tensorflow/.eggs/pbr-3.1.1-py3.5.egg/pbr/packaging.py", line 705, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "/usr/lib/python3.5/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.5/email/parser.py", line 54, in parse
        data = fp.read(8192)
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 824: ordinal not in range(128)
    error in setup command: Error parsing /tmp/pip-build-bl_kidhk/spotify-tensorflow/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 824: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bl_kidhk/spotify-tensorflow/
```

**Comment by nevillelyh** [comment]
Turns out I need to `export LANG=C.UTF-8` in the container.
