### ISSUE TITLE
spotify-tf install fails on python3.5

### ISSUE THREAD

**Issue by yonromai** [spotify/spotify-tensorflow#71]
```
Collecting spotify-tensorflow==0.3.2 (from -r /home/workspace/ml-paved-road-pipeline/tf-supervised/src/main/python/core-requirements.txt (line 3))
  Downloading https://pypi.spotify.net/spotify/production/packages/65/fe/c568a1d6574c72e7cf12527ac15cf8b431fa6d3cd644abf2b7f28f44a1c3/spotify_tensorflow-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/util.py", line 259, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/packaging.py", line 806, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "/tmp/pip-install-xr0p5imi/spotify-tensorflow/.eggs/pbr-4.1.0-py3.5.egg/pbr/packaging.py", line 774, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "/usr/lib/python3.5/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.5/email/parser.py", line 54, in parse
        data = fp.read(8192)
      File "/home/workspace/ml-paved-road-pipeline/target/.tox/mypy/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 896: ordinal not in range(128)
    error in setup command: Error parsing /tmp/pip-install-xr0p5imi/spotify-tensorflow/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 896: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xr0p5imi/spotify-tensorflow/

ERROR: could not install deps [-r/home/workspace/ml-paved-road-pipeline/tf-supervised/src/main/python/test-requirements.txt]; v = InvocationError('/home/workspace/ml-paved-road-pipeline/target/.tox/mypy/bin/pip install -r/home/workspace/ml-paved-road-pipeline/tf-supervised/src/main/python/test-requirements.txt (see /home/workspace/ml-paved-road-pipeline/target/.tox/mypy/log/mypy-1.log)', 1)
```

**Comment by yonromai** [comment]
same error in `python3.4`

**Comment by andrewsmartin** [comment]
Seems this is still an issue - gonna reopen.

**Comment by brianmartin** [comment]
I'm not able to repro:


```
$ python --version
Python 3.7.0
$ pip --version
pip 10.0.1 from /Users/brianm/src/github/spotify/spotify-tensorflow/venv3/lib/python3.7/site-packages/pip-10.0.1-py3.7.egg/pip (python 3.7)
$ pip install spotify-tensorflow
Collecting spotify-tensorflow
  Using cached https://files.pythonhosted.org/packages/be/7a/fad855e8c3ead46db0a7bf292ad26e5dab574389047ae48daf8d4678b069/spotify_tensorflow-0.5.1.tar.gz
Requirement already satisfied: six<2.0.0,>=1.11.0 in ./venv3/lib/python3.7/site-packages (from spotify-tensorflow) (1.11.0)
Requirement already satisfied: pandas<1.0.0,>=0.22.0 in ./venv3/lib/python3.7/site-packages (from spotify-tensorflow) (0.23.4)
Requirement already satisfied: numpy<2.0.0,>=1.14.0 in ./venv3/lib/python3.7/site-packages (from spotify-tensorflow) (1.15.4)
Requirement already satisfied: typing<4.0.0,>=3.6.4 in ./venv3/lib/python3.7/site-packages (from spotify-tensorflow) (3.6.6)
Requirement already satisfied: tensorflow_metadata<1.0.0,>=0.6.0 in ./venv3/lib/python3.7/site-packages (from spotify-tensorflow) (0.9.0)
Requirement already satisfied: pytz>=2011k in ./venv3/lib/python3.7/site-packages (from pandas<1.0.0,>=0.22.0->spotify-tensorflow) (2018.7)
Requirement already satisfied: python-dateutil>=2.5.0 in ./venv3/lib/python3.7/site-packages (from pandas<1.0.0,>=0.22.0->spotify-tensorflow) (2.7.5)
Requirement already satisfied: protobuf<4,>=3.6.0 in ./venv3/lib/python3.7/site-packages (from tensorflow_metadata<1.0.0,>=0.6.0->spotify-tensorflow) (3.6.1)
Requirement already satisfied: googleapis-common-protos in ./venv3/lib/python3.7/site-packages (from tensorflow_metadata<1.0.0,>=0.6.0->spotify-tensorflow) (1.5.5)
Requirement already satisfied: setuptools in ./venv3/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg (from protobuf<4,>=3.6.0->tensorflow_metadata<1.0.0,>=0.6.0->spotify-tensorflow) (39.1.0)
Installing collected packages: spotify-tensorflow
  Running setup.py install for spotify-tensorflow ... done
Successfully installed spotify-tensorflow-0.5.1
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by andrewsmartin** [comment]
@brianmartin looks like that's working for python 3.7, how about 3.5 - does that work for you?

**Comment by brianmartin** [comment]
Ah, so I can't repro by unsetting my LANG but I see @fallonchen from your discussion internally that it's related to our usage of `pbr` which has a bug which doesn't allow unicode in the package description. (See: https://bugs.launchpad.net/pbr/+bug/1704472)

Would be good to get a repro here if we hope to fix. Something like: `$ docker run python pip install spotify-tensorflow` (which is failing for a different reason: no tensorflow_metadata for python 3?).

**Comment by andrewsmartin** [comment]
Re-opening this as this is now an issue on the latest AI platform runtime.
